#!/bin/bash
#
# Updates the food log stuff periodically
printf "Content-Type: text/html\n\n"
printf '<html><head></head><body><a href=/and/test/pages/index.html>Back to Food Menu</a>'

cd /big/dom/xkirkbird/cgi-bin/ft/

# Put new files into the system; set default times and meals
printf "Running process\n"
python process.py 

# Create an updated database based on the files (it's essentially read only)
# I would put in some sort of backup if it was read-write
# As it is, lets create in a new file and then rename over
temp_loc=`/bin/mktemp --tmpdir foodlog-XXXXXX.sqlite`
printf "Creating database\n"
python create_db.py $temp_loc /big/dom/xkirkbird/www/and/test/byday/  /big/dom/xkirkbird/www/and/test/templates/

(cd /big/dom/xkirkbird/www/and/test/byday/ && mv current.sqlite previous.sqlite && mv $temp_loc current.sqlite)

printf "Creating Full Edit Reversed\n"
python create_range.py --title "Full Edit Reversed" --edit --reverse --cgi '/cgi-bin/ft/' /big/dom/xkirkbird/www/and/test/byday/current.sqlite -o /big/dom/xkirkbird/www/and/test/pages/list.html

# Tasks to create various reports from the database
printf "Creating Edit This Week\n"
python create_range.py --title "Edit Last Week" --cgi '/cgi-bin/ft/' -w --edit /big/dom/xkirkbird/www/and/test/byday/current.sqlite -o /big/dom/xkirkbird/www/and/test/pages/last_week.html
printf "Creating Edit Last Week\n"
python create_range.py --title "Edit This Week" --edit --cgi '/cgi-bin/ft/' --now /big/dom/xkirkbird/www/and/test/byday/current.sqlite -o /big/dom/xkirkbird/www/and/test/pages/this_week.html


printf "Creating Full List\n"
python create_range.py --title "Full List" --cgi '/cgi-bin/ft/' --reverse /big/dom/xkirkbird/www/and/test/byday/current.sqlite -o /big/dom/xkirkbird/www/and/test/pages/list_diet.html

# Tasks to create various reports from the database
printf "Creating Last Week\n"
python create_range.py --title "Meals from Last Week"  --cgi '/cgi-bin/ft/' -w /big/dom/xkirkbird/www/and/test/byday/current.sqlite -o /big/dom/xkirkbird/www/and/test/pages/last_week_diet.html
printf "Creating This Week\n"
python create_range.py --title "Meals this week"  --cgi '/cgi-bin/ft/' --now /big/dom/xkirkbird/www/and/test/byday/current.sqlite -o /big/dom/xkirkbird/www/and/test/pages/this_week_diet.html


printf "</body></html>"

