#!/bin/bash
#
# Updates the food log stuff periodically
cd /big/dom/xkirkbird/cgi-bin/ft/

# Put new files into the system; set default times and meals
python process.py 

# Create a list of all the meals to allow editing from
# This could be done from the database, right now it's done from the files.
python list_form.py > /big/dom/xkirkbird/www/and/test/pages/list.html 

# Create an updated database based on the files (it's essentially read only)
# I would put in some sort of backup if it was read-write
# As it is, lets create in a new file and then rename over
temp_loc=`/bin/mktemp --tmpdir foodlog-XXXXXX.sqlite`
python create_db.py $temp_loc /big/dom/xkirkbird/www/and/test/byday/ 
(cd /big/dom/xkirkbird/www/and/test/byday/ && mv current.sqlite previous.sqlite && mv $temp_loc current.sqlite)

# Tasks to create various reports from the database
python write_range.py -w ../www/and/test/byday/current.sqlite > /big/dom/xkirkbird/www/and/test/pages/this_week.html

